### ISSUE TITLE
Data transfer not working for DMagic experiments

### ISSUE THREAD

**Issue by zkovacs-epam** [KerboKatz/AutomatedScienceSampler#7]
The experiments are deployed correctly along with stock experiments, but the data is not transferred to any container (tried: command pods, lander cans, experiment storage container). Stock experiments are transferred correctly automatically.

According to the log it is transferred, while in reality, it is not:
[LOG 21:59:35.136] [AutomatedScienceSampler] dmNAlbedoScan: Experiment is deployed
[LOG 21:59:35.137] [AutomatedScienceSampler] dmNAlbedoScan: We can transfer the science!
[LOG 21:59:35.138] [AutomatedScienceSampler] dmNAlbedoScan: transfering
[LOG 21:59:35.138] [AutomatedScienceSampler] Experiment checked in: 8.3945

Cheers

update: fixed typo

**Comment by tivec** [comment]
I'll leave a comment on this - I've got the same issue. I've got a vessel with one of each type of crew driving around the KSC equipped with a large amount of experiments. Everything is nicely transferred, except for the magnetometer boom from dmagic.

**Comment by tivec** [comment]
Below is the full log for a magnetometer boom not transfering. If I review the data for the magnetometer, it's listed as 1.5 science, 5 Mits of data.
```
[LOG 20:35:51.044] [AutomatedScienceSampler] AutoScience is off
[LOG 20:35:51.061] [AutomatedScienceSampler] AutoScience is off
[LOG 20:35:51.077] [AutomatedScienceSampler] False Single ce213745-56fd-465d-a05a-5c7795ea7977
[LOG 20:35:51.079] [AutomatedScienceSampler] Saving settings. Updating UI took: 0.0008. Total: 1.5354
[LOG 20:35:51.081] [AutomatedScienceSampler] Removing ModuleScienceExperiment as transfer target
[LOG 20:35:51.081] [AutomatedScienceSampler] Removing ModuleScienceExperiment as transfer target
[LOG 20:35:51.082] [AutomatedScienceSampler] Removing DMModuleScienceAnimate as transfer target
[LOG 20:35:51.082] [AutomatedScienceSampler] Removing DMModuleScienceAnimate as transfer target
[LOG 20:35:51.082] [AutomatedScienceSampler] Removing DMModuleScienceAnimate as transfer target
[LOG 20:35:51.083] [AutomatedScienceSampler] Removing ModuleScienceExperiment as transfer target
[LOG 20:35:52.090] [AutomatedScienceSampler] 0.0102
[LOG 20:35:52.091] [AutomatedScienceSampler] crewReport: CanRunExperiment
[LOG 20:35:52.091] [AutomatedScienceSampler] Deploying RetroMk1inline (Rvr 2) for :1.5 science! crewReport@KerbinSrfLandedRunway
[LOG 20:35:52.092] [AutomatedScienceSampler] crewReport: DeployExperiment
[LOG 20:35:52.092] [Experiments]: Setting FX Modules to 1...
[LOG 20:35:52.093] [Experiments]: FX Modules set: 1
[LOG 20:35:52.093] [AutomatedScienceSampler] crewReport@KerbinSrfLandedRunway_New
[LOG 20:35:52.093] [AutomatedScienceSampler] Experiment checked in: 2.9216
[LOG 20:35:52.094] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:52.094] [AutomatedScienceSampler] Deploying dmmagBoom for :1.5 science! magScan@KerbinSrfLandedRunway
[LOG 20:35:52.095] [AutomatedScienceSampler] magScan@KerbinSrfLandedRunway_New
[LOG 20:35:52.095] [AutomatedScienceSampler] Experiment checked in: 5.161
[LOG 20:35:52.096] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:52.096] [AutomatedScienceSampler] temperatureScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:52.097] [AutomatedScienceSampler] temperatureScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:52.097] [AutomatedScienceSampler] temperatureScan: Experiment isn't inoperable
[LOG 20:35:52.098] [AutomatedScienceSampler] Experiment checked in: 7.3994
[LOG 20:35:52.098] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:52.099] [AutomatedScienceSampler] barometerScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:52.099] [AutomatedScienceSampler] barometerScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:52.100] [AutomatedScienceSampler] barometerScan: Experiment isn't inoperable
[LOG 20:35:52.100] [AutomatedScienceSampler] Experiment checked in: 9.6198
[LOG 20:35:52.100] [AutomatedScienceSampler] Microwaves: CanRunExperiment
[LOG 20:35:52.101] [AutomatedScienceSampler] Deploying Microwaves for :2.4 science! Microwaves@KerbinSrfLandedRunway
[LOG 20:35:52.101] [AutomatedScienceSampler] Microwaves: DeployExperiment
[LOG 20:35:52.102] [Experiments]: Setting FX Modules to 1...
[LOG 20:35:52.102] [Experiments]: FX Modules set: 1
[LOG 20:35:52.102] [AutomatedScienceSampler] Microwaves@KerbinSrfLandedRunway_New
[LOG 20:35:52.103] [AutomatedScienceSampler] Experiment checked in: 12.439
[LOG 20:35:52.103] [AutomatedScienceSampler] seismicScan: CanRunExperiment
[LOG 20:35:52.104] [AutomatedScienceSampler] Deploying sensorAccelerometer for :6 science! seismicScan@KerbinSrfLandedRunway
[LOG 20:35:52.104] [AutomatedScienceSampler] seismicScan: DeployExperiment
[LOG 20:35:52.105] [Experiments]: Setting FX Modules to 1...
[LOG 20:35:52.105] [Experiments]: FX Modules set: 1
[LOG 20:35:52.105] [AutomatedScienceSampler] seismicScan@KerbinSrfLandedRunway_New
[LOG 20:35:52.106] [AutomatedScienceSampler] Experiment checked in: 15.2687
[LOG 20:35:52.106] [AutomatedScienceSampler] Total: 15.6517
[LOG 20:35:53.127] [AutomatedScienceSampler] 0.0079
[LOG 20:35:53.128] [AutomatedScienceSampler] crewReport: CanRunExperiment
[LOG 20:35:53.128] [AutomatedScienceSampler] crewReport: Science value is less than cutoff threshold: 0<1
[LOG 20:35:53.129] [AutomatedScienceSampler] crewReport: CanTransfer
[LOG 20:35:53.129] [AutomatedScienceSampler] crewReport: We can transfer the science!
[LOG 20:35:53.129] [AutomatedScienceSampler] crewReport: transfering
[LOG 20:35:53.130] [Experiments]: Setting FX Modules to 0...
[LOG 20:35:53.130] [Experiments]: FX Modules set: 0
[LOG 20:35:53.130] [AutomatedScienceSampler] Experiment checked in: 3.3461
[LOG 20:35:53.131] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:53.131] [AutomatedScienceSampler] magScan: Science value is less than cutoff threshold: 0<1
[LOG 20:35:53.132] [AutomatedScienceSampler] magScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:53.132] [AutomatedScienceSampler] magScan: Experiment isn't inoperable
[LOG 20:35:53.133] [AutomatedScienceSampler] Experiment checked in: 5.5393
[LOG 20:35:53.133] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:53.134] [AutomatedScienceSampler] temperatureScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:53.134] [AutomatedScienceSampler] temperatureScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:53.134] [AutomatedScienceSampler] temperatureScan: Experiment isn't inoperable
[LOG 20:35:53.135] [AutomatedScienceSampler] Experiment checked in: 7.7906
[LOG 20:35:53.135] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:53.136] [AutomatedScienceSampler] barometerScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:53.136] [AutomatedScienceSampler] barometerScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:53.137] [AutomatedScienceSampler] barometerScan: Experiment isn't inoperable
[LOG 20:35:53.137] [AutomatedScienceSampler] Experiment checked in: 10.044
[LOG 20:35:53.138] [AutomatedScienceSampler] Microwaves: CanRunExperiment
[LOG 20:35:53.138] [AutomatedScienceSampler] Microwaves: Science value is less than cutoff threshold: 0<1
[LOG 20:35:53.138] [AutomatedScienceSampler] Microwaves: CanTransfer
[LOG 20:35:53.139] [AutomatedScienceSampler] Microwaves: We can transfer the science!
[LOG 20:35:53.139] [AutomatedScienceSampler] Microwaves: transfering
[LOG 20:35:53.140] [Experiments]: Setting FX Modules to 0...
[LOG 20:35:53.140] [Experiments]: FX Modules set: 0
[LOG 20:35:53.140] [AutomatedScienceSampler] Experiment checked in: 13.3018
[LOG 20:35:53.141] [AutomatedScienceSampler] seismicScan: CanRunExperiment
[LOG 20:35:53.141] [AutomatedScienceSampler] seismicScan: Science value is less than cutoff threshold: 0.545455<1
[LOG 20:35:53.142] [AutomatedScienceSampler] seismicScan: CanTransfer
[LOG 20:35:53.142] [AutomatedScienceSampler] seismicScan: We can transfer the science!
[LOG 20:35:53.143] [AutomatedScienceSampler] seismicScan: transfering
[LOG 20:35:53.143] [Experiments]: Setting FX Modules to 0...
[LOG 20:35:53.143] [Experiments]: FX Modules set: 0
[LOG 20:35:53.144] [AutomatedScienceSampler] Experiment checked in: 16.5522
[LOG 20:35:53.144] [AutomatedScienceSampler] Total: 16.9466
[LOG 20:35:54.159] [AutomatedScienceSampler] 0.0109
[LOG 20:35:54.160] [AutomatedScienceSampler] crewReport: CanRunExperiment
[LOG 20:35:54.160] [AutomatedScienceSampler] crewReport: Science value is less than cutoff threshold: 0<1
[LOG 20:35:54.161] [AutomatedScienceSampler] crewReport: CanTransfer
[LOG 20:35:54.161] [AutomatedScienceSampler] crewReport: Experiment has no data skiping transfer 0
[LOG 20:35:54.162] [AutomatedScienceSampler] crewReport: CanReset
[LOG 20:35:54.162] [AutomatedScienceSampler] crewReport: Experiment isn't inoperable
[LOG 20:35:54.163] [AutomatedScienceSampler] Experiment checked in: 3.0715
[LOG 20:35:54.163] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:54.163] [AutomatedScienceSampler] magScan: Science value is less than cutoff threshold: 0<1
[LOG 20:35:54.164] [AutomatedScienceSampler] magScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:54.164] [AutomatedScienceSampler] magScan: Experiment isn't inoperable
[LOG 20:35:54.165] [AutomatedScienceSampler] Experiment checked in: 5.3243
[LOG 20:35:54.165] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:54.166] [AutomatedScienceSampler] temperatureScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:54.166] [AutomatedScienceSampler] temperatureScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:54.167] [AutomatedScienceSampler] temperatureScan: Experiment isn't inoperable
[LOG 20:35:54.167] [AutomatedScienceSampler] Experiment checked in: 7.652
[LOG 20:35:54.168] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:54.168] [AutomatedScienceSampler] barometerScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:54.169] [AutomatedScienceSampler] barometerScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:54.169] [AutomatedScienceSampler] barometerScan: Experiment isn't inoperable
[LOG 20:35:54.169] [AutomatedScienceSampler] Experiment checked in: 10.0499
[LOG 20:35:54.170] [AutomatedScienceSampler] Microwaves: CanRunExperiment
[LOG 20:35:54.171] [AutomatedScienceSampler] Microwaves: Science value is less than cutoff threshold: 0<1
[LOG 20:35:54.171] [AutomatedScienceSampler] Microwaves: CanTransfer
[LOG 20:35:54.171] [AutomatedScienceSampler] Microwaves: Experiment has no data skiping transfer 0
[LOG 20:35:54.172] [AutomatedScienceSampler] Microwaves: CanReset
[LOG 20:35:54.172] [AutomatedScienceSampler] Microwaves: Experiment isn't inoperable
[LOG 20:35:54.173] [AutomatedScienceSampler] Experiment checked in: 13.2491
[LOG 20:35:54.173] [AutomatedScienceSampler] seismicScan: CanRunExperiment
[LOG 20:35:54.174] [AutomatedScienceSampler] seismicScan: Science value is less than cutoff threshold: 0.545455<1
[LOG 20:35:54.174] [AutomatedScienceSampler] seismicScan: CanTransfer
[LOG 20:35:54.174] [AutomatedScienceSampler] seismicScan: Experiment has no data skiping transfer 0
[LOG 20:35:54.175] [AutomatedScienceSampler] seismicScan: CanReset
[LOG 20:35:54.175] [AutomatedScienceSampler] seismicScan: Experiment isn't inoperable
[LOG 20:35:54.176] [AutomatedScienceSampler] Experiment checked in: 16.2284
[LOG 20:35:54.176] [AutomatedScienceSampler] Total: 16.6245
[LOG 20:35:55.209] [AutomatedScienceSampler] 0.0073
[LOG 20:35:55.209] [AutomatedScienceSampler] crewReport: CanRunExperiment
[LOG 20:35:55.210] [AutomatedScienceSampler] crewReport: Science value is less than cutoff threshold: 0<1
[LOG 20:35:55.210] [AutomatedScienceSampler] crewReport: CanTransfer
[LOG 20:35:55.211] [AutomatedScienceSampler] crewReport: Experiment has no data skiping transfer 0
[LOG 20:35:55.211] [AutomatedScienceSampler] crewReport: CanReset
[LOG 20:35:55.211] [AutomatedScienceSampler] crewReport: Experiment isn't inoperable
[LOG 20:35:55.212] [AutomatedScienceSampler] Experiment checked in: 3.0249
[LOG 20:35:55.212] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:55.213] [AutomatedScienceSampler] magScan: Science value is less than cutoff threshold: 0<1
[LOG 20:35:55.213] [AutomatedScienceSampler] magScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:55.214] [AutomatedScienceSampler] magScan: Experiment isn't inoperable
[LOG 20:35:55.214] [AutomatedScienceSampler] Experiment checked in: 5.2634
[LOG 20:35:55.215] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:55.215] [AutomatedScienceSampler] temperatureScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:55.215] [AutomatedScienceSampler] temperatureScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:55.216] [AutomatedScienceSampler] temperatureScan: Experiment isn't inoperable
[LOG 20:35:55.216] [AutomatedScienceSampler] Experiment checked in: 7.5366
[LOG 20:35:55.217] [AutomatedScienceSampler] Runway_SrfLanded_False
[LOG 20:35:55.217] [AutomatedScienceSampler] barometerScan: Science value is less than cutoff threshold: 0.9<1
[LOG 20:35:55.218] [AutomatedScienceSampler] barometerScan: Experiment has no data skiping transfer. Data found: 0_0
[LOG 20:35:55.218] [AutomatedScienceSampler] barometerScan: Experiment isn't inoperable
[LOG 20:35:55.219] [AutomatedScienceSampler] Experiment checked in: 9.809
[LOG 20:35:55.219] [AutomatedScienceSampler] Microwaves: CanRunExperiment
[LOG 20:35:55.220] [AutomatedScienceSampler] Microwaves: Science value is less than cutoff threshold: 0<1
[LOG 20:35:55.220] [AutomatedScienceSampler] Microwaves: CanTransfer
[LOG 20:35:55.220] [AutomatedScienceSampler] Microwaves: Experiment has no data skiping transfer 0
[LOG 20:35:55.221] [AutomatedScienceSampler] Microwaves: CanReset
[LOG 20:35:55.221] [AutomatedScienceSampler] Microwaves: Experiment isn't inoperable
[LOG 20:35:55.222] [AutomatedScienceSampler] Experiment checked in: 12.7488
[LOG 20:35:55.222] [AutomatedScienceSampler] seismicScan: CanRunExperiment
[LOG 20:35:55.222] [AutomatedScienceSampler] seismicScan: Science value is less than cutoff threshold: 0.545455<1
[LOG 20:35:55.223] [AutomatedScienceSampler] seismicScan: CanTransfer
```

**Comment by Xarun** [comment]
Thanks for the log but i need the whole log file. Reason behind that is that ASS outputs certain info on load as well that can be very useful in this case.
You'll have to turn on debug and restart the game in order to get that info.

**Comment by tivec** [comment]
![](http://i.imgur.com/V9AoTMT.png)
[KSP.zip](https://github.com/KerboKatz/AutomatedScienceSampler/files/1133251/KSP.zip)
I have attached the log file. As you can see on the screenshot, the scan (dmNAlbedoScan) has a science value of 1.4 points, so it should be over my threshold of 0.5.

**Comment by anothergene** [comment]
I'm having the same issue.  not related to universal storage.  appears to be any experiment (stock or not) that has to be reset by scientists. Even though there is a scientists on board.  Anything like the thermometer or pressure test works fine.    Attached is the full player.log withe debug turned on for some testing I did today.  

[Player.log.zip](https://github.com/KerboKatz/AutomatedScienceSampler/files/1137509/Player.log.zip)

**Comment by zkovacs-epam** [comment]
@anothergene 
I tested with materials lab and goo canister, and they transfer and reset (if scientist present) correctly. 
In contrast, the surface hydrogen scan can be used multiple times without a scientist, and still does not transfer.
Also, it is not related (afaik) to universal storage (the universal storage version of stock experiments transfer correctly), but to DMagic orbital science.

**Comment by tivec** [comment]
Can confirm that the stock experiments in Universal Storage work fine, but not the DMagic ones...

**Comment by zkovacs-epam** [comment]
bump?

**Comment by GoAhead-at** [comment]
is there anything missing to fix this annoying bug?

**Comment by Xarun** [comment]
@GoAhead-at mostly missing time to do anything.

**Comment by Xarun** [comment]
I just released a new pre release that should hopefully fix this issue. Didn't have much time to test it thoroughly. So please report any issues you encounter!

**Comment by zkovacs-epam** [comment]
Thank you very much!
"mostly missing time to do anything." - that's a song every developer know XD

**Comment by Tickwick** [comment]
1.3.4 doesn't load for me for some reason, works fine when going back to 1.3.3.

**Comment by zkovacs-epam** [comment]
Hi Xarun!

I think the issue is back (or something very similar) on 1.3.5-KSP1.8

The DMagic and Universal Storage II materials science and goo modules do not transfer the experiments to the designated pod, nor do they reset properly. They also get in some bugged state where you can't manually reset or take the sample from them either.

Stock modules work fine.
DMagic and USII modules work fine manually.

Regards
